### ISSUE TITLE
Problem in IE

### ISSUE THREAD

**Issue by ghost** [kappys1/angular2-carousel#2]
Hi,
working excellent in chrome ,firefox.but in IE i am getting cube mode like this...and mouse moves very hard...not as like in other browser...

is there any solutions?? 
is there any changes in css file??

In IE:
-----
![vani_ie](https://user-images.githubusercontent.com/35024564/34483657-efabf3c0-efe5-11e7-8215-2d315a0dbfc2.png)

In firefox:
------------
![screenshot from 2018-01-02 17-54-51](https://user-images.githubusercontent.com/35024564/34483684-2a47782e-efe6-11e7-8858-9280ae339808.png)

**Comment by kappys1** [comment]
Is possible that is a browser problem...
This should fixed with [issue #1](https://github.com/kappys1/angular2-carousel/issues/1)
![image](https://user-images.githubusercontent.com/12160420/34485958-8778893e-efcd-11e7-97b5-61dce29b3ffd.png)

you can check that the perspective is only available with version 11...
let me see if I found any solution!

Thanks

**Comment by kappys1** [comment]
@nomulavani sorry for responding too late

I think that this question was resolved in this [issue](https://github.com/kappys1/angular2-carousel/issues/1)
