### ISSUE TITLE
center carousel item clicked???

### ISSUE THREAD

**Issue by vikasgudi** [kappys1/angular2-carousel#9]
how to check whether the carousel item clicked , is the center carousel item or not?????

**Comment by kappys1** [comment]
I think that is not a issue,

You can to do it to many ways
for example: 
- In html, if the .item-carousel is static, you can set a click event in the center carousel item.
- Or if is content to load is dynamic you can set a click event in all items and in your controller check if is the center or not , knowing the length of content and passing the index of item clicked etc..
- Or in html check if is the center item with *ngIf and generate a tag with click or not if it is. 

I close the issue because I think this is not a issue but the people can help you.

If do you like the library, you can to give me a star =) 
thanks
